version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports: ["2181:2181"]

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on: [zookeeper]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports: ["29092:29092", "9092:9092"]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: cx_analytics
      POSTGRES_USER: cxuser
      POSTGRES_PASSWORD: cxpass
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  event-ingestion-service:
    build: ./event-ingestion-service
    depends_on: [kafka]
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    ports: ["8081:8081"]

  analytics-service:
    build: ./analytics-service
    depends_on: [kafka, postgres, redis]
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cx_analytics
      SPRING_DATASOURCE_USERNAME: cxuser
      SPRING_DATASOURCE_PASSWORD: cxpass
      REDIS_HOST: redis
    ports: ["8082:8082"]

  api-service:
    build: ./api-service
    depends_on: [postgres, redis]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cx_analytics
      SPRING_DATASOURCE_USERNAME: cxuser
      SPRING_DATASOURCE_PASSWORD: cxpass
      REDIS_HOST: redis
    ports: ["8080:8080"]

  dashboard-web:
    build: ./dashboard-web
    depends_on: [api-service]
    ports: ["3000:80"]